### PR TITLE
Parse Scottish population data

### LINKED ISSUE #270: Handling new demographic data
We now have a temporary repository with Scotland census data in hdf5 format, broken down by age into 5 year categories, at https://github.com/ScottishCovidResponse/temporary_data.
This needs to be fed into the model example run: Scottish_run.jl (still pending PR ScottishCovidResponse/Simulation.jl#38) instead of the current .tif file.
In the first instance this will probably need to be the 10km grid instead of 1km and will involve some kind of mapping between the grid id numbers supplied with the data and the x,y position in space, which should be available soon.

### PR DESCRIPTION
**Pull request by eperim**
Closes https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/270

@claireh93 was this what you had in mind with the Scottish population data?

### CODE REVIEW

**Comment by claireh93** [comment]
Hi @eperim, this looks good! The only thing I would say is that we are reading in the demographic data, summing it and then splitting it apart randomly over age categories again in lines 75-79. I think we need to work out a way to input the age-aggregated data into `simplehabitatAE`, but maybe that's worth adding as a new issue? I also think something might be erroring out during testing?

**Comment by eperim** [comment]
Oh cool. I will take another look and make sure that the ages are preserved.

About the CI failure, the issue is lack of memory for the CI runners. It works fine locally (and for one of the CI runners), but it seems that the data is too big for some of them. An alternative could be creating a smaller dataset for the test to mitigate this. Or maybe @jwscook has a better idea?

File: examples/Epidemiology/Scotland_run.jl [hunk 1]
```diff
@@ -44,15 +43,16 @@ param = SEI2HRDGrowth(birth_rates, death_rates, ageing,
...
 
 # Read in population sizes for Scotland
-scotpop = Array{Float64, 2}(readfile(Simulation.path("test", "examples",
-                                                     "ScotlandDensity2011.tif"),
-                               0.0, 7e5, 5e5, 1.25e6))
-# Coarsen grid to 10km
-scotpop = [sum(scotpop[i:i+9, j:j+9]) for i in 1:10:size(scotpop, 1), j in 1:10:size(scotpop, 2)]
+scotpop = parse_scotpop(Simulation.path("test", "examples", "scrc_demographics.h5"))
+# Sum up age categories and turn into simple matrix
+total_pop = Matrix(sum(scotpop, dims=3)[:, :])
```
Comment (wytbella) [inline examples/Epidemiology/Scotland_run.jl]: I _think_ you can have `total_pop` as an AxisArray Matrix now, preserving the grid x, y information

Comment (eperim) [reply examples/Epidemiology/Scotland_run.jl]: That works, indeed, I'll change that.

File: examples/Epidemiology/Scotland_run.jl [hunk 2]
```diff
@@ -8,8 +8,18 @@ using Distributions
 
 do_plot = false
 
+# Read in population sizes for Scotland
+scotpop = parse_scotpop(Simulation.path("test", "examples", "scrc_demographics.h5"), grid="1k")
```
Comment (eperim) [inline examples/Epidemiology/Scotland_run.jl]: I changed this to the 1k x 1k grid, instead of the 10k x 10k grid because https://github.com/ScottishCovidResponse/Simulation.jl/pull/41/files#diff-e8c26f5226daa3e1cdde61c294185a66R76 would break otherwise.

With the large grid, the Julia process simply gets killed, which might suggest it's trying to allocate too much stuff in memory. Not sure if this is expected or if it might be the symptom of something being inefficient, but it should be investigated separately from this PR.

File: examples/Epidemiology/Scotland_run.jl [hunk 3]
```diff
@@ -74,15 +75,13 @@ rel = Gauss{eltype(epienv.habitat)}()
...
-    epi.abundances.matrix[cat_idx[:, 1], j] .= split_pop[j]
-end
+# Populate susceptibles according to actual population spread
+reshaped_pop = reshape(scotpop, size(scotpop, 1) * size(scotpop, 2), size(scotpop, 3))'
+epi.abundances.matrix[cat_idx[:, 1], :] = reshaped_pop
 
 # Add in initial infections randomly (samples weighted by population size)
 N_cells = size(epi.abundances.matrix, 2)
-samp = sample(weights(1.0 .* epi.abundances.matrix[1, :]), 100)
+samp = sample(1:N_cells, weights(1.0 .* sum(epi.abundances.matrix, dims=1)), 100)
```
Comment (eperim) [inline examples/Epidemiology/Scotland_run.jl]: @claireh93 please double check the logic here, because I am computing the weights differently from before. I add up over all disease classes (only susceptible should be non-zero) and over all ages, in order to get the total population size of each cell.

Also, I think there might be an issue with this part, because in the part below we add individuals to `Exposed`, but never remove them from `Susceptible`, so we are effectively adding more individuals to the total population.

**Comment by eperim** [comment]
Using this data, even if we adopt the 1k x 1k grid, there is no way this example will run in an average laptop, because of
```
abuns = zeros(Int64, size(epi.abundances.matrix, 1), N_cells, 366)
```
being a gigantic array, equivalent to a 48678 per 1million matrix. Should we be ok with this only running on the large clusters or should we coarsen it down?

**Comment by richardreeve** [comment]
As @sdl1 says in SCRC-309, we can store records in an hdf5 file in slices as we go along, so we don't need to have the 366 deep array, we can just have the current state. We can also reduce the size of the integers we are using to UInt16 and still cover everywhere in the UK with a factor of 4 spare even with only 1 demographic group and everyone susceptible (Islington is approx 16k/sq km). We have a final problem that 75% of Scotland is sea, which is wasteful of space, despite the fact that the update step is pretty efficient at ignoring these inactive squares. All of those together would take us down to 1MB rather than 6GB for Scotland!

In the meanwhile running it at 10km should be fine - I'm not sure what you mean [here](https://github.com/ScottishCovidResponse/Simulation.jl/pull/41#discussion_r432882542) by it breaking?

File: examples/Epidemiology/Scotland_run.jl (hunk 3 above)
Comment (richardreeve) [reply examples/Epidemiology/Scotland_run.jl]: Shall we just add 100 exposed people in total (rather than the current 100 x 10) by doing 100 multinomial draws from the whole `epi.abundances.matrix` susceptibles? Then subtract them from from the susceptible column and add them to the exposed.

File: examples/Epidemiology/Scotland_run.jl (hunk 2 above)
Comment (richardreeve) [reply examples/Epidemiology/Scotland_run.jl]: I think this is a bug in `parse_scotpop()`. See comments there.

File: src/Epidemiology/data_utils.jl [hunk 4]
```diff
@@ -0,0 +1,39 @@
...
+    )
+
+    data = h5read(path, "scotland_2018")
+
+    # Get age brackets
+    ages = [string(5*i)*"-"*string(5*i+4) for i in 0:17]
+    push!(ages, "90+")
+
+    # Create empty grid
+    grid_size = parse(Int, chop(grid)) * 1000
```
Comment (richardreeve) [inline src/Epidemiology/data_utils.jl]: At the moment this is the wrong way round - should be `1000 ÷ parse(Int, chop(grid))`. But the maximum x and y axes should be `maximum(parse.(Int, getindex.(split.(data["grid1k_id"], repeat(["-"], length(data["grid1k_id"]))), 1)))` and `maximum(parse.(Int, getindex.(split.(data["grid1k_id"], repeat(["-"], length(data["grid1k_id"]))), 2)))`, though there's definitely a cleaner way of doing this! That way you can make the `grid_size` as tight as possible.

File: src/Epidemiology/data_utils.jl [hunk 5]
```diff
@@ -0,0 +1,39 @@
+using HDF5
+
+"""
+    parse_scotpop(path; grid="10k")
```
Comment (richardreeve) [inline src/Epidemiology/data_utils.jl]: Can we make this `parse_hdf5()` and add a component argument?

File: examples/Epidemiology/Scotland_run.jl (hunk 2 above)
Comment (richardreeve) [reply examples/Epidemiology/Scotland_run.jl]: Can we also use `parse_hdf5()` and add `component="scotland_2018"` here please?

File: src/Epidemiology/data_utils.jl [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+
+    # Get age brackets
+    ages = [string(5*i)*"-"*string(5*i+4) for i in 0:17]
+    push!(ages, "90+")
+
+    # Create empty grid
+    grid_size = parse(Int, chop(grid)) * 1000
+    population = AxisArray(
+        zeros(grid_size, grid_size, length(ages)),
+        grid_x=collect(1:grid_size),
```
Comment (richardreeve) [inline src/Epidemiology/data_utils.jl]: If we're using `AxisArray`s, is there any reason not to add in the right grid size in km?

File: src/Simulation.jl [hunk 7]
```diff
@@ -122,6 +122,9 @@ export DiversitySet, updatesimulation!, gettimes
 include("Biodiversity/AdditionalDiversity.jl")
 export meta_simpson, meta_shannon, meta_speciesrichness, mean_abun, geom_mean_abun, sorenson, pd, makeunique
 
+include("Epidemiology/data_utils.jl")
+export parse_scotpop
```
Comment (richardreeve) [inline src/Simulation.jl]: `parse_hdf5`

File: test/test_data_utils.jl [hunk 8]
```diff
@@ -0,0 +1,9 @@
+@testset "Data Utils" begin
+    path = Simulation.path("test", "examples", "scrc_demographics.h5")
+    scotpop_10k = parse_scotpop(path)
```
Comment (richardreeve) [inline test/test_data_utils.jl]: `component="scotland_2018"`

File: test/test_data_utils.jl [hunk 9]
```diff
@@ -0,0 +1,9 @@
...
+    @test size(scotpop_10k) == (10000, 10000, 19)
+    scotpop_1k = parse_scotpop(path, grid="1k")
```
Comment (richardreeve) [inline test/test_data_utils.jl]: ditto

File: test/test_data_utils.jl [hunk 10]
```diff
@@ -0,0 +1,9 @@
...
+    @test size(scotpop_1k) == (1000, 1000, 19)
```
Comment (richardreeve) [inline test/test_data_utils.jl]: fix

File: test/test_data_utils.jl [hunk 11]
```diff
@@ -0,0 +1,9 @@
...
+    @test sum(scotpop_1k) == sum(scotpop_10k)
+    @test_throws ArgumentError parse_scotpop(path, grid="5k")
```
Comment (richardreeve) [inline test/test_data_utils.jl]: fix

**Review by richardreeve — CHANGES_REQUESTED** [review]
Looks good, but there's a problem with the grid creation in `parse_scotpop()` and a couple of other small issues.

File: examples/Epidemiology/Scotland_run.jl (hunk 3 above)
Comment (eperim) [reply examples/Epidemiology/Scotland_run.jl]: The susceptible is not a column, though, but a matrix. From which age to we subtract from/add to?

File: src/Epidemiology/data_utils.jl (hunk 4 above)
Comment (eperim) [reply src/Epidemiology/data_utils.jl]: Not sure I get the reasoning here. We have the option of a 1,000 by 1,000 grid or of a 10,000 by 10,000 grid, isn't it? That is what `grid_size` is getting. `1000 ÷ parse(Int, chop(grid))` will be either 1,000 or 100.

Are you suggesting to not include in the matrix cells that have zero count?

File: src/Epidemiology/data_utils.jl (hunk 6 above)
Comment (eperim) [reply src/Epidemiology/data_utils.jl]: I am not sure I have that information.

File: test/test_data_utils.jl (hunk 10 above)
Comment (eperim) [reply test/test_data_utils.jl]: Sorry, but fix what?

File: test/test_data_utils.jl (hunk 11 above)
Comment (eperim) [reply test/test_data_utils.jl]: Sorry, but fix what?

**Comment by eperim** [comment]
> I'm not sure what you mean [here](https://github.com/ScottishCovidResponse/Simulation.jl/pull/41#discussion_r432882542) by it breaking?

The Julia process gets killed, without a stack trace. That usually happens when allocating something too large in memory. e.g:
```julia
julia> A = zeros(1000000, 1000000)
[1]    6691 killed     /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia --project=@.
```

File: test/test_data_utils.jl (hunk 11 above)
Comment (richardreeve) [reply test/test_data_utils.jl]: Sorry - parse_scotpop is now parse_hdf5.

File: test/test_data_utils.jl (hunk 10 above)
Comment (richardreeve) [reply test/test_data_utils.jl]: Sorry - the sizes will now be wrong won't they? Again, this is a misunderstanding about the 1k and 10k meanings.

File: src/Epidemiology/data_utils.jl (hunk 6 above)
Comment (richardreeve) [reply src/Epidemiology/data_utils.jl]: That's the "1k" or "10k" isn't it?

Comment (richardreeve) [reply src/Epidemiology/data_utils.jl]: See above for comment on kms...

File: examples/Epidemiology/Scotland_run.jl (hunk 3 above)
Comment (richardreeve) [reply examples/Epidemiology/Scotland_run.jl]: We just draw from the whole human abundances matrix, weighted by abundance in that matrix. Since everyone is susceptible, that'll draw from all of the susceptible populations in all age classes. Then we just move those individuals from susceptible to exposed.

File: src/Epidemiology/data_utils.jl (hunk 4 above)
Comment (richardreeve) [reply src/Epidemiology/data_utils.jl]: Ah, I have suddenly realised that you misunderstood what 1k and 10k referred to! It's the size of a grid square in km. It should probably be renamed to 1km and 10km to make that more explicit if I've now realised what's going on? And then I'm proposing only using the grid size that the file actually uses.

**Comment by richardreeve** [comment]
Right - I think I understand now. All of this is a confusion about what 1k means. We'll fix the component name in a future version of the file!

**Review by richardreeve — APPROVED** [review]
