### PR TITLE
Fix bug in how the initial infecteds are populated.

### LINKED ISSUE #424: Investigate thread heisenbug when params.births appear to have negative numbers
I got this error with `JULIA_NUM_THREADS=4` and `JULIA_NUM_THREADS=8` but have had trouble reproducing it.

```bash
$julia examples/Epidemiology/Scotland_run.jl 
Creating Diversity to Phylo interface...
ERROR: LoadError: TaskFailedException:
ArgumentError: Binomial: the condition n >= zero(n) is not satisfied.
Stacktrace:
 [1] macro expansion at /home/cookj/.julia/packages/Distributions/RAeyY/src/utils.jl:6 [inlined]
 [2] #Binomial#29 at /home/cookj/.julia/packages/Distributions/RAeyY/src/univariate/discrete/binomial.jl:34 [inlined]
 [3] Binomial at /home/cookj/.julia/packages/Distributions/RAeyY/src/univariate/discrete/binomial.jl:33 [inlined]
 [4] macro expansion at /home/cookj/Documents/code/Simulation.jl/src/Epidemiology/EpiGenerate.jl:109 [inlined]
 [5] (::Simulation.var"#280#threadsfor_fun#115"{EpiSystem{GridEpiEnv{ContinuousHab{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}},NoControl},EpiList{Simulation.EpiParams{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}}},Gauss{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}}},Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}},Simulation.EpiParams{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}},Int64,Int64,UnitRange{Int64}})(::Bool) at ./threadingconstructs.jl:61
 [6] (::Simulation.var"#280#threadsfor_fun#115"{EpiSystem{GridEpiEnv{ContinuousHab{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}},NoControl},EpiList{Simulation.EpiParams{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}}},Gauss{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}}},Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}},Simulation.EpiParams{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}},Int64,Int64,UnitRange{Int64}})() at ./threadingconstructs.jl:28
Stacktrace:
 [1] wait(::Task) at ./task.jl:267
 [2] macro expansion at ./threadingconstructs.jl:69 [inlined]
 [3] classupdate! at /home/cookj/Documents/code/Simulation.jl/src/Epidemiology/EpiGenerate.jl:96 [inlined]
 [4] update!(::EpiSystem{GridEpiEnv{ContinuousHab{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}},NoControl},EpiList{Simulation.EpiParams{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}}},Gauss{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}) at /home/cookj/Documents/code/Simulation.jl/src/Epidemiology/EpiGenerate.jl:15
 [5] simulate_record!(::Array{Int64,3}, ::EpiSystem{GridEpiEnv{ContinuousHab{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}},NoControl},EpiList{Simulation.EpiParams{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}}},Gauss{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(yr,),𝐓,nothing}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}; save::Bool, save_path::String) at /home/cookj/Documents/code/Simulation.jl/src/Epidemiology/EpiHelper.jl:122
 [6] simulate_record!(::Array{Int64,3}, ::EpiSystem{GridEpiEnv{ContinuousHab{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}},NoControl},EpiList{Simulation.EpiParams{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}}},Gauss{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(yr,),𝐓,nothing}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}) at /home/cookj/Documents/code/Simulation.jl/src/Epidemiology/EpiHelper.jl:73
 [7] macro expansion at ./util.jl:175 [inlined]
 [8] run() at /home/cookj/Documents/code/Simulation.jl/examples/Epidemiology/Scotland_run.jl:135
 [9] top-level scope at /home/cookj/Documents/code/Simulation.jl/examples/Epidemiology/Scotland_run.jl:153
 [10] include(::Module, ::String) at ./Base.jl:377
 [11] exec_options(::Base.JLOptions) at ./client.jl:288
 [12] _start() at ./client.jl:484
in expression starting at /home/cookj/Documents/code/Simulation.jl/examples/Epidemiology/Scotland_run.jl:153
                                                         [ 2m 37s284 | Jun 09 11:56am > Jun 09 11:58am ]
```

### PR DESCRIPTION
**Pull request by claireh93**
Closes ScottishCovidResponse/SCRCIssueTracking#424

Found problem with negative abundances that appeared every so often - isolated problem instead to EpiSystem set up, where the indexing on adding exposed/removing susceptible individuals was wrong.

### CODE REVIEW

File: examples/Epidemiology/Scotland_run.jl [hunk 1]
```diff
@@ -120,11 +120,14 @@ N_cells = size(epi.abundances.matrix, 2)
...
 cell_ids = getfield.(samp, 2)
-# Add to exposed
-epi.abundances.matrix[vcat(cat_idx[age_ids, 2]...), cell_ids] .= 1
-# Remove from susceptible
-epi.abundances.matrix[vcat(cat_idx[age_ids, 1]...), cell_ids] =
-    epi.abundances.matrix[vcat(cat_idx[age_ids, 1]...), cell_ids] .- 1
+
+for i in eachindex(age_ids)
+    # Add to exposed
+    epi.abundances.matrix[vcat(cat_idx[age_ids[i], 2]...), cell_ids[i]] .= 1
```
Comment (richardreeve) [inline examples/Epidemiology/Scotland_run.jl]: Can't we get rid of the `vcat(...)`? Isn't it just `cat_idx[age_ids[i], 2]`? Also, presumably you should check that `epi.abundances.matrix[cat_idx[age_ids[i], 1], cell_ids[i]] > 0` before you do this in case you've selected a 1 twice?

File: examples/Epidemiology/Scotland_run.jl [hunk 2]
```diff
@@ -120,11 +120,14 @@ N_cells = size(epi.abundances.matrix, 2)
...
+    # Remove from susceptible
+    epi.abundances.matrix[vcat(cat_idx[age_ids[i], 1]...), cell_ids[i]] =
+        epi.abundances.matrix[vcat(cat_idx[age_ids[i], 1]...), cell_ids[i]] .- 1
```
Comment (richardreeve) [inline examples/Epidemiology/Scotland_run.jl]: Is this just `epi.abundances.matrix[cat_idx[age_ids[i], 1], cell_ids[i]] .-= 1`

**Review by richardreeve — CHANGES_REQUESTED** [review]
Minor fix?

**Comment by claireh93** [comment]
@richardreeve okay those suggestions should be resolved now!

**Review by richardreeve — APPROVED** [review]
